### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [pavel-sudomoin/yandex-praktikum-project-10#1]
Добрый день.

Отлично:
- Соблюдены требования к веткам
- Есть .gitignore
- Прекраснейшее резюме
- Полностью реализована проверка email

**Надо исправить:**
- Из-за атрибута **novalidate** cейчас можно отправить пустые поля. Форма должна отправляться только в случае успешной валидации всех полей.
- Сейчас все инпуты имеют одинаковый атрибут name="name", хотя такой name подходит только полю: "Имя"
- Есть проблемы валидации:
1. Имя:
- Проходят невалидное имя: `Я-Я` (имена или части имени должны содержать минимум 2 буквы)
2. Проходят валидацию следующие невалидные телефонные номера:
- `+7 (925-900-90-90`
- `+7925) 900-90-90`
3. Проходит валидацию такие IP-адрес: `http://www.255.255.255.255`
4. Не выполнено задание по допущению в конце IP-адреса/урла порта.

Можно лучше:
- Есть пустой файл `script.js`. Лишних файлов в проектах не должно быть

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by pavel-sudomoin** [comment]
Добрый день.
Исправления внесены, выпущена версия v2.0.0

**Comment by mrprovoker** [comment]
Отличная работа, все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!
